apiVersion: batch/v1
kind: CronJob
metadata:
  name: sample-quartzkube-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: job
            image: quartz-job-runner:latest
            env:
            - name: JOB_CLASS
              value: com.quartzkube.examples.HelloWorldJob
