apiVersion: batch/v1
kind: Job
metadata:
  name: sample-quartzkube-job
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: job
        image: quartz-job-runner:latest
        env:
        - name: JOB_CLASS
          value: com.quartzkube.examples.HelloWorldJob
