apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "hello-world-job.fullname" . }}
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: job
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: JOB_CLASS
          value: {{ .Values.jobClass | quote }}
